name: Update Teer Results

on:
  workflow_dispatch:
  # Enable this only after manual testing is successful
  schedule:
  - cron: "*/5 * * * *"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  update-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies without modifying repo
        run: npm install axios cheerio --no-save

      - name: Run result updater
        run: node assets/scripts/update-results.js

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add data/all-results.json

          if git diff --cached --quiet; then
            echo "No JSON changes found."
            exit 0
          fi

          git commit -m "Auto update teer results"
          git push